import { chromium, type Page, type BrowserContext } from '@playwright/test'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { ALL_PHASES } from '../../src/data/phases'
import { resolveLocalizedCode } from '../../src/lib/localization'
import { isEnglishProse } from './language-isolation'

/**
 * Works through the whole app as a learner, in both languages, and writes down what it
 * finds instead of stopping at the first problem.
 *
 * Everything else in scripts/audit reads source or data. This opens the app. That
 * distinction has mattered more than any other in this repository: seven checkers all
 * reported zero while every correct answer in twelve phases was being marked incomplete,
 * because the data was right and the app was wrong.
 *
 * It runs each exercise TWICE — once in English, once in Portuguese — because a defect
 * that only appears in one language is invisible to a run in the other, and most of the
 * worst ones found so far were Portuguese-only.
 *
 * Two kinds of check, so no phase is skipped:
 *
 *   with a reference solution   submit it and require a pass. Phases 0-20.
 *   without one                 still open the exercise and read the screen: does it
 *                               render, does the editor load, is the visible text in the
 *                               learner's language. Phases 21-68 get this today, and
 *                               graduate to the first kind as references are written.
 *
 * The report is appended after every phase, so a run that is interrupted is still worth
 * reading. Learner progress is cleared when the run ends, so the next one starts from
 * phase 0 with nothing unlocked.
 *
 *   npx tsx scripts/audit/learner-agent.ts                    # everything, both languages
 *   npx tsx scripts/audit/learner-agent.ts --phases=0-8       # a range
 *   npx tsx scripts/audit/learner-agent.ts --langs=pt         # one language
 *   npx tsx scripts/audit/learner-agent.ts --keep-progress    # do not reset at the end
 */

const BASE = process.env.HP_BASE || 'http://127.0.0.1:4173'
const arg = (name: string, fallback: string) =>
  process.argv.find(item => item.startsWith(`--${name}=`))?.split('=')[1] ?? fallback

const [FROM, TO] = arg('phases', '0-68').split('-').map(Number)
const LANGS = arg('langs', 'en,pt').split(',').filter(Boolean) as Array<'en' | 'pt'>
const KEEP_PROGRESS = process.argv.includes('--keep-progress')
const REPORT_DIR = 'audit-reports'

/**
 * Fail loudly rather than quietly checking less.
 *
 * This used to be `existsSync(...) ? JSON.parse(...) : {}`, and nothing in the repository
 * wrote the file. On any machine but the one where a one-off command had produced it, the
 * run submitted no solutions at all and reported that every graded exercise was fine. An
 * empty reference set is not a smaller run; it is a run that cannot fail.
 */
const REFERENCES_PATH = process.env.HP_REFERENCES || '/tmp/references.json'
if (!existsSync(REFERENCES_PATH)) {
  console.error(`no reference solutions at ${REFERENCES_PATH}`)
  console.error('run: python3 scripts/audit/dump-references.py   (npm run audit:learner does this for you)')
  process.exit(1)
}
const REFERENCES: Record<string, string> = JSON.parse(readFileSync(REFERENCES_PATH, 'utf8'))
if (Object.keys(REFERENCES).length === 0) {
  console.error(`${REFERENCES_PATH} is empty — every graded exercise would be skipped and the run would pass`)
  process.exit(1)
}

interface Finding {
  phase: number
  exercise: string
  lang: string
  kind: string
  detail: string
}

const findings: Finding[] = []
let checked = 0

function record(finding: Finding) {
  findings.push(finding)
  console.log(`  ✗ [${finding.lang}] ${finding.exercise}: ${finding.kind} — ${finding.detail.slice(0, 120)}`)
}

/** Written after every phase so an interrupted run still leaves something readable. */
function writeReport() {
  mkdirSync(REPORT_DIR, { recursive: true })
  writeFileSync(`${REPORT_DIR}/learner-agent.json`, JSON.stringify({ checked, findings }, null, 1))

  const byPhase = new Map<number, Finding[]>()
  for (const finding of findings) {
    if (!byPhase.has(finding.phase)) byPhase.set(finding.phase, [])
    byPhase.get(finding.phase)!.push(finding)
  }

  const lines = [
    '# What a learner hits',
    '',
    `Generated by \`scripts/audit/learner-agent.ts\` — phases ${FROM}–${TO}, languages ${LANGS.join(' and ')}.`,
    '',
    `**${checked} exercise runs checked. ${findings.length} problems.**`,
    '',
  ]
  if (!findings.length) lines.push('No problems found.', '')
  for (const [phase, items] of [...byPhase].sort((a, b) => a[0] - b[0])) {
    lines.push(`## Phase ${phase}`, '')
    for (const item of items) {
      lines.push(`- **${item.exercise}** \`${item.lang}\` — *${item.kind}*`, `  > ${item.detail.replace(/\n/g, ' ').slice(0, 400)}`, '')
    }
  }
  writeFileSync(`${REPORT_DIR}/learner-agent.md`, lines.join('\n'))
}

async function setLanguage(page: Page, lang: 'en' | 'pt') {
  const button = page.getByRole('button', { name: lang.toUpperCase(), exact: true })
  if (await button.count()) await button.first().click().catch(() => {})
  await page.waitForTimeout(600)
}

async function setCode(page: Page, code: string) {
  const surface = page.getByTestId('python-editor-surface').first()
  await surface.waitFor({ state: 'visible', timeout: 20_000 })
  for (let i = 0; i < 40; i++) {
    if (await surface.getAttribute('data-editor-ready') === 'true') break
    await page.waitForTimeout(250)
  }
  await surface.evaluate((node, next) => {
    node.dispatchEvent(new CustomEvent('hp:set-code', { detail: next }))
  }, code)
  for (let i = 0; i < 40; i++) {
    if (await surface.getAttribute('data-editor-value') === code) return true
    await page.waitForTimeout(250)
  }
  return false
}

async function satisfyThinkingGate(page: Page, lang: 'en' | 'pt') {
  const prediction = page.getByTestId('exercise-prediction')
  if (!(await prediction.count())) return
  await prediction.fill(lang === 'pt'
    ? 'Deve imprimir o resultado que o enunciado descreve.'
    : 'It should print the result the task describes.').catch(() => {})
  await page.getByTestId('exercise-change-plan').fill(lang === 'pt'
    ? 'Executar uma vez e ajustar conforme a saída.'
    : 'Run it once, then adjust based on the output.').catch(() => {})
}

async function runAndRead(page: Page) {
  const button = page.getByTestId('exercise-run-button').first()
  await button.waitFor({ state: 'visible', timeout: 20_000 })
  for (let i = 0; i < 60; i++) {
    if (await button.isEnabled()) break
    await page.waitForTimeout(500)
  }
  if (!(await button.isEnabled())) {
    const reason = await page.getByTestId('exercise-run-requirements').first().innerText().catch(() => '')
    return { blocked: true, feedback: reason.replace(/\s+/g, ' ').trim() }
  }
  await button.click()
  let feedback = ''
  for (let i = 0; i < 80; i++) {
    await page.waitForTimeout(500)
    feedback = await page.getByTestId('exercise-feedback').first().innerText().catch(() => '')
    if (feedback && !/running|executando/i.test(feedback)) break
  }
  return { blocked: false, feedback: feedback.replace(/\s+/g, ' ').trim() }
}

/**
 * Reads the task as rendered and reports English prose shown to a Portuguese learner.
 * Only in PT: English text in English mode is not a defect.
 */
// A line ending in ':' after a keyword is a Python block header, not a sentence. Without
// the second half of this, the run reported `if amount > 10000:` and `elif age < 60:` as
// English prose — three findings that pointed at nothing to fix and buried the real ones.
const LOOKS_LIKE_CODE = /[=(){}\[\]]|^\s*#|^\s*"""|\bprint\b|\bdef\b|\bfor\b .*:|___|^(if|elif|else|for|while|try|except|finally|with|class|def)\b.*:\s*$|[<>]=?|^[\w.-]+\.\w{1,4}$|^\w+(,\w+)+$/

/**
 * Words that are this exercise's own vocabulary, not English prose.
 *
 * A run of phases 9-20 reported fourteen leaks and every one was Portuguese:
 *
 *     "Usa as chaves sku e name"
 *     "Calcule a taxa como amount multiplicado por rate"
 *     "Vazio preserva start"
 *
 * `sku`, `name`, `amount`, `rate`, `start` are variables the task is telling the learner
 * to use. Naming them in Portuguese prose is correct — renaming them would break the
 * exercise — so they are read out of the code and excluded before the language test.
 */
function neutralWords(...code: string[]): Set<string> {
  const names = new Set<string>()
  for (const source of code) {
    for (const match of (source || '').matchAll(/[A-Za-z_][A-Za-z_0-9]*/g)) names.add(match[0].toLowerCase())
  }
  return names
}

function languageLeaks(text: string, neutral: Set<string> = new Set()): string[] {
  // The page body includes the editor. Code is not prose, and it has its own check
  // (audit:language), so scanning it here reports variable names as English and buries
  // the findings that matter under noise.
  const withoutIdentifiers = (line: string) =>
    line.replace(/[A-Za-z_][A-Za-z_0-9]*/g, word => (neutral.has(word.toLowerCase()) ? ' ' : word))

  return [...new Set(text.split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 12 && !LOOKS_LIKE_CODE.test(line) && isEnglishProse(withoutIdentifiers(line))))]
    .slice(0, 3)
}

const browser = await chromium.launch({
  executablePath: process.env.HP_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
})
const phases = ALL_PHASES.filter(p => p.id >= FROM && p.id <= TO).sort((a, b) => a.id - b.id)

/**
 * One fresh learner per language.
 *
 * Sharing a session between the two passes is not a smaller version of the same
 * experiment — it is a different one. Once the English pass completes an exercise, the
 * app re-selects the first INCOMPLETE exercise on load, so the Portuguese pass kept
 * being pulled back to exercise 1 no matter how many times the tab was clicked. Three
 * retries could not beat it, because the app was right and the harness was wrong.
 *
 * A new context also means the second language starts with nothing unlocked, which is
 * what a real learner in that language has.
 */
for (const lang of LANGS) {
  const context: BrowserContext = await browser.newContext({ viewport: { width: 1280, height: 1100 } })
  const page = await context.newPage()

  await page.goto(BASE, { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(1500)
  await page.locator('.hp-guest-entry').click().catch(() => {})
  await page.waitForTimeout(1000)

  /**
   * Prove the app actually booted before walking 69 phases through it.
   *
   * A build made without VITE_SUPABASE_URL renders a "configuration required" screen on
   * every route. The run did not report that: the screen has plenty of text, so the
   * "did the page render" check passed, and the missing editor meant every poll for
   * `data-editor-value` waited out Playwright's 30-second default. One exercise took ten
   * minutes and produced no finding. The run looked slow rather than wrong, which is the
   * worse of the two failures.
   */
  const firstScreen = await page.locator('body').innerText().catch(() => '')
  if (/CONFIGURA[ÇC][ÃA]O NECESS[ÁA]RIA|CONFIGURATION REQUIRED|SUPABASE_ANON_KEY/i.test(firstScreen)) {
    console.error('\nthe app under test is showing its configuration screen, not the course.')
    console.error('build it with the audit stub first:  bash scripts/audit/local-ci.sh')
    console.error('or set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY and re-run `npm run build`.')
    process.exit(1)
  }
  console.log(`\n╔══ LANGUAGE: ${lang.toUpperCase()} — fresh learner, nothing unlocked`)

  for (const phase of phases) {
    console.log(`\n═══ PHASE ${phase.id}  (${phase.exercises.length} exercises)`)

    for (const [index, exercise] of phase.exercises.entries()) {
      await page.goto(`${BASE}/phase/${phase.id}/exercises`, { waitUntil: 'domcontentloaded' }).catch(() => {})
      await page.waitForTimeout(1600)
      await setLanguage(page, lang)

      // Click, then CONFIRM, then retry. Switching language re-renders the tab row, so a
      // click issued immediately after can land on a detached node and do nothing at all —
      // silently, leaving the previous exercise on screen. Three attempts, and if the
      // starter never appears the finding says so instead of grading the wrong exercise.
      const wanted = resolveLocalizedCode(exercise.starterCode as never, lang).trim()
      // A short timeout, because this is a POLL. With Playwright's 30-second default,
      // twenty polls against a page with no editor took ten minutes and said nothing.
      const editorValue = () => page.getByTestId('python-editor-surface').first()
        .getAttribute('data-editor-value', { timeout: 1000 }).catch(() => null)

      let opened = false
      for (let attempt = 0; attempt < 3 && !opened; attempt++) {
        for (const label of [`Exercise ${index + 1}`, `Exercício ${index + 1}`]) {
          const tab = page.getByRole('button', { name: label, exact: true })
          if (await tab.count()) { await tab.first().click().catch(() => {}); break }
        }
        await page.waitForTimeout(700)

        for (const label of ['Restore starter code', 'Restaurar código inicial']) {
          const reset = page.getByRole('button', { name: label, exact: true })
          if (await reset.count()) { await reset.first().click().catch(() => {}); break }
        }
        for (let i = 0; i < 20; i++) {
          const now = await editorValue()
          if (!wanted || (now !== null && now.trim() === wanted)) { opened = true; break }
          await page.waitForTimeout(250)
        }
      }

      const body = await page.locator('body').innerText().catch(() => '')
      if (body.length < 60) {
        record({ phase: phase.id, exercise: exercise.id, lang, kind: 'page did not render', detail: body.slice(0, 120) })
        continue
      }

      // Identity: the starter is unique per exercise, so it proves which one is on screen.
      const onScreen = await editorValue()
      if (onScreen === null) {
        record({
          phase: phase.id, exercise: exercise.id, lang,
          kind: 'no code editor on the page',
          detail: body.replace(/\s+/g, ' ').slice(0, 160),
        })
        continue
      }
      const expected = wanted
      if (expected && onScreen !== null && onScreen.trim() !== expected) {
        // Show WHERE they diverge. "did not match" is a verdict; the first differing
        // characters are a diagnosis, and this check has already been wrong twice —
        // once because a saved draft was on screen, once because the comparison itself
        // was at fault rather than the app.
        let at = 0
        const actual = onScreen.trim()
        while (at < expected.length && at < actual.length && expected[at] === actual[at]) at += 1
        record({
          phase: phase.id, exercise: exercise.id, lang,
          kind: 'the editor did not hold this exercise starter',
          detail: `diverges at ${at}: expected ${JSON.stringify(expected.slice(at, at + 60))}, on screen ${JSON.stringify(actual.slice(at, at + 60))}`,
        })
        continue
      }

      if (lang === 'pt') {
        const neutral = neutralWords(wanted, REFERENCES[exercise.id] || '')
        for (const leak of languageLeaks(body, neutral)) {
          record({ phase: phase.id, exercise: exercise.id, lang, kind: 'English shown to a Portuguese learner', detail: leak })
        }
      }

      const reference = REFERENCES[exercise.id]
      if (!reference) {
        checked++
        continue                                   // rendered and read; nothing to submit yet
      }

      if (!(await setCode(page, resolveLocalizedCode(reference, lang)))) {
        record({ phase: phase.id, exercise: exercise.id, lang, kind: 'editor refused the solution', detail: 'data-editor-value never matched what was set' })
        continue
      }
      await satisfyThinkingGate(page, lang)

      const result = await runAndRead(page)
      checked++
      if (result.blocked) {
        record({ phase: phase.id, exercise: exercise.id, lang, kind: 'Run stayed disabled', detail: result.feedback || 'no reason shown' })
        continue
      }
      const passed = /✓/.test(result.feedback) && !/✗|precisa corrigir|needs attention/i.test(result.feedback)
      if (!passed) {
        record({ phase: phase.id, exercise: exercise.id, lang, kind: 'a correct solution FAILED', detail: result.feedback })
      } else {
        console.log(`  ✓ [${lang}] ${exercise.id}`)
      }
    }
    writeReport()
  }

  if (!KEEP_PROGRESS) {
    // Leave nothing behind, so the next run is the same experiment as this one.
    await page.evaluate(async () => {
      try { localStorage.clear(); sessionStorage.clear() } catch { /* blocked */ }
      if (indexedDB.databases) {
        for (const db of await indexedDB.databases()) if (db.name) indexedDB.deleteDatabase(db.name)
      }
    }).catch(() => {})
  }
  await context.close()
}

if (!KEEP_PROGRESS) console.log('\nlearner progress cleared — the next run starts from phase 0')


writeReport()
console.log(`\n${checked} exercise runs checked, ${findings.length} problems`)
console.log(`report: ${REPORT_DIR}/learner-agent.md`)
await browser.close()
process.exitCode = findings.length ? 1 : 0
