import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

/**
 * Guards for the v10.26 remediation.
 *
 * Both audit decks were produced against a dist/ build that was six days stale, so
 * several findings described code that had already changed. These assertions pin
 * the fixes to the source itself, which is the thing that actually ships.
 */
describe('v10.26 remediation — accessibility and installability', () => {
  it('lets a learner pinch-zoom (WCAG 2.1 SC 1.4.4)', () => {
    const html = read('../index.html')
    const viewport = html.match(/<meta name="viewport"[^>]*content="([^"]+)"/)?.[1] ?? ''
    expect(viewport).toContain('width=device-width')
    expect(viewport).toContain('viewport-fit=cover')
    expect(viewport).not.toContain('maximum-scale')
    expect(viewport).not.toContain('user-scalable=no')
  })

  it('declares exactly one manifest, generated by vite-plugin-pwa', () => {
    const html = read('../index.html')
    // A second hardcoded <link rel="manifest"> made the browser honour whichever
    // came first and silently ignore the other; the two files had already drifted.
    expect(html).not.toContain('rel="manifest"')
    expect(html).not.toContain('manifest.json')
  })

  it('gives the app a stable identity and no orientation lock', () => {
    const config = read('../vite.config.ts')
    // Without id, a browser can treat a redeploy as a new app and drop this
    // origin's storage — which here is the learner's progress.
    expect(config).toMatch(/id:\s*'\/'/)
    expect(config).toMatch(/display_override:/)
    expect(config).not.toMatch(/orientation:\s*'portrait-primary'/)
  })
})

describe('v10.26 remediation — offline data integrity', () => {
  it('never caches Supabase auth responses to disk', () => {
    const config = read('../vite.config.ts')
    expect(config).toMatch(/auth\\\/v1/)
    expect(config).toContain("handler: 'NetworkOnly'")
    // Auth must be registered before the REST route: Workbox matches in order.
    expect(config.indexOf('NetworkOnly')).toBeLessThan(config.indexOf("cacheName: 'supabase-rest-v1'"))
  })

  it('bounds the Supabase REST cache instead of letting it grow forever', () => {
    const config = read('../vite.config.ts')
    expect(config).toMatch(/expiration:\s*\{\s*maxEntries:\s*60/)
    expect(config).toMatch(/cacheableResponse:\s*\{\s*statuses:\s*\[200\]/)
  })

  it('queues every cloud write that fails instead of swallowing it', () => {
    for (const path of ['./lib/syncedStore.ts', './lib/codeDrafts.ts', './lib/learningSync.ts']) {
      const source = read(path)
      expect(source, `${path} must hand failed writes to the outbox`).toContain('enqueueMutation')
    }
    // The old codeDrafts message promised a retry that did not exist.
    expect(read('./lib/codeDrafts.ts')).not.toContain('cloud sync will retry')
  })

  it('never lets a server row overwrite a write that is still queued', () => {
    const source = read('./lib/syncedStore.ts')
    // Timestamps alone cannot decide this: a device with a slow clock would judge
    // its own fresh write older than the stale server row and discard it.
    expect(source).toContain('pendingRowValues')
    expect(source).toContain('queued.has(row.key)')
    // Trigger-maintained column, immune to client clock skew.
    expect(source).toContain('server_updated_at')
  })

  it('drains the outbox and installs deploy recovery at startup', () => {
    const main = read('./main.tsx')
    expect(main).toContain('installOutboxDrain()')
    // appUpdate.ts existed with zero importers, so its recovery never ran.
    expect(main).toContain('installAppUpdateRecovery()')
  })

  it('lets stored completion state correct an optimistic local pass', () => {
    const source = read('./pages/Exercises.tsx')
    // `{ ...done, ...previous }` made a local `true` permanent, so a completion whose
    // write failed stayed green through every reload and still unlocked the quiz.
    expect(source).not.toContain('...done, ...previous')
    expect(source).toContain('...previous, ...done')
  })
})

describe('v10.26 remediation — failures are visible', () => {
  it('actually uses the toast system that was mounted but never called', () => {
    const source = read('./pages/Exercises.tsx')
    expect(source).toContain('useToast()')
    expect(source).toContain('showToast(')
  })

  it('guards the terminal CTA against duplicate submits', () => {
    const source = read('./pages/Exercises.tsx')
    expect(source).toContain('completeLock')
    expect(source).toContain('loading={completing}')
    // A rejection used to be an unhandled promise and a visibly dead button.
    expect(source).toMatch(/markStepDone[\s\S]{0,400}catch/)
  })

  it('restores a half-typed sign-up without ever storing the password', () => {
    const login = read('./pages/Login.tsx')
    expect(login).toContain('hp_login_draft_v1')
    // The stored shape is pinned deliberately. Adding `password` here would leave a
    // plaintext credential in web storage on a shared family device — worse than
    // the lost-form-state problem it would be solving.
    expect(login).toContain('JSON.stringify({ mode, email, displayName }')
    expect(login).not.toMatch(/setItem\([^)]*password/)
    // Cleared on success so the next person on the device sees an empty form.
    expect(login).toContain('clearDraft()')
  })

  it('localises auth errors instead of printing Supabase English', () => {
    const login = read('./pages/Login.tsx')
    expect(login).toContain('authErrorMessage')
    expect(login).not.toContain('caught.message')
    expect(login).not.toContain('setError(authError.message)')
  })
})
