/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedModeSelectRouteImport } from './routes/_authenticated/mode-select'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedClaimsIndexRouteImport } from './routes/_authenticated/claims.index'
import { Route as AuthenticatedPlannerFieldDayRouteImport } from './routes/_authenticated/planner.field-day'
import { Route as AuthenticatedPlannerAdminRouteImport } from './routes/_authenticated/planner.admin'
import { Route as AuthenticatedClaimsNewRouteImport } from './routes/_authenticated/claims.new'
import { Route as AuthenticatedClaimsBatchRouteImport } from './routes/_authenticated/claims.batch'
import { Route as AuthenticatedClaimsClaimIdRouteImport } from './routes/_authenticated/claims.$claimId'
import { Route as AuthenticatedCatReportDeploymentIdRouteImport } from './routes/_authenticated/cat-report.$deploymentId'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedClaimsMapRouteImport } from './routes/_authenticated/claims-map'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeSelectRoute = AuthenticatedModeSelectRouteImport.update({
  id: '/mode-select',
  path: '/mode-select',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedClaimsIndexRoute =
  AuthenticatedClaimsIndexRouteImport.update({
    id: '/claims/',
    path: '/claims/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerFieldDayRoute =
  AuthenticatedPlannerFieldDayRouteImport.update({
    id: '/field-day',
    path: '/field-day',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedPlannerAdminRoute =
  AuthenticatedPlannerAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedClaimsNewRoute = AuthenticatedClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsBatchRoute =
  AuthenticatedClaimsBatchRouteImport.update({
    id: '/claims/batch',
    path: '/claims/batch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClaimsClaimIdRoute =
  AuthenticatedClaimsClaimIdRouteImport.update({
    id: '/claims/$claimId',
    path: '/claims/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatReportDeploymentIdRoute =
  AuthenticatedCatReportDeploymentIdRouteImport.update({
    id: '/cat-report/$deploymentId',
    path: '/cat-report/$deploymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsMapRoute = AuthenticatedClaimsMapRouteImport.update({
  id: '/claims-map',
  path: '/claims-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/mode-select': typeof AuthenticatedModeSelectRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/claims-map': typeof AuthenticatedClaimsMapRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/today': typeof AuthenticatedTodayRoute
  '/cat-report/$deploymentId': typeof AuthenticatedCatReportDeploymentIdRoute
  '/claims/$claimId': typeof AuthenticatedClaimsClaimIdRoute
  '/claims/batch': typeof AuthenticatedClaimsBatchRoute
  '/claims/new': typeof AuthenticatedClaimsNewRoute
  '/planner/admin': typeof AuthenticatedPlannerAdminRoute
  '/planner/field-day': typeof AuthenticatedPlannerFieldDayRoute
  '/claims/': typeof AuthenticatedClaimsIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/mode-select': typeof AuthenticatedModeSelectRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/claims-map': typeof AuthenticatedClaimsMapRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/today': typeof AuthenticatedTodayRoute
  '/cat-report/$deploymentId': typeof AuthenticatedCatReportDeploymentIdRoute
  '/claims/$claimId': typeof AuthenticatedClaimsClaimIdRoute
  '/claims/batch': typeof AuthenticatedClaimsBatchRoute
  '/claims/new': typeof AuthenticatedClaimsNewRoute
  '/planner/admin': typeof AuthenticatedPlannerAdminRoute
  '/planner/field-day': typeof AuthenticatedPlannerFieldDayRoute
  '/claims': typeof AuthenticatedClaimsIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRoute
  '/_authenticated/mode-select': typeof AuthenticatedModeSelectRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/claims-map': typeof AuthenticatedClaimsMapRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/cat-report/$deploymentId': typeof AuthenticatedCatReportDeploymentIdRoute
  '/_authenticated/claims/$claimId': typeof AuthenticatedClaimsClaimIdRoute
  '/_authenticated/claims/batch': typeof AuthenticatedClaimsBatchRoute
  '/_authenticated/claims/new': typeof AuthenticatedClaimsNewRoute
  '/_authenticated/planner/admin': typeof AuthenticatedPlannerAdminRoute
  '/_authenticated/planner/field-day': typeof AuthenticatedPlannerFieldDayRoute
  '/_authenticated/claims/': typeof AuthenticatedClaimsIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/deployments'
    | '/mode-select'
    | '/calls'
    | '/claims-map'
    | '/plan'
    | '/planner'
    | '/profile'
    | '/today'
    | '/cat-report/$deploymentId'
    | '/claims/$claimId'
    | '/claims/batch'
    | '/claims/new'
    | '/planner/admin'
    | '/planner/field-day'
    | '/claims/'
    | '/planner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/deployments'
    | '/mode-select'
    | '/plan'
    | '/profile'
    | '/today'
    | '/cat-report/$deploymentId'
    | '/claims/$claimId'
    | '/claims/batch'
    | '/claims/new'
    | '/planner/admin'
    | '/planner/field-day'
    | '/claims'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/deployments'
    | '/_authenticated/mode-select'
    | '/_authenticated/plan'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/today'
    | '/_authenticated/cat-report/$deploymentId'
    | '/_authenticated/claims/$claimId'
    | '/_authenticated/claims/batch'
    | '/_authenticated/claims/new'
    | '/_authenticated/planner/admin'
    | '/_authenticated/planner/field-day'
    | '/_authenticated/claims/'
    | '/_authenticated/planner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mode-select': {
      id: '/_authenticated/mode-select'
      path: '/mode-select'
      fullPath: '/mode-select'
      preLoaderRoute: typeof AuthenticatedModeSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/claims/': {
      id: '/_authenticated/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof AuthenticatedClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/field-day': {
      id: '/_authenticated/planner/field-day'
      path: '/field-day'
      fullPath: '/planner/field-day'
      preLoaderRoute: typeof AuthenticatedPlannerFieldDayRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/planner/admin': {
      id: '/_authenticated/planner/admin'
      path: '/admin'
      fullPath: '/planner/admin'
      preLoaderRoute: typeof AuthenticatedPlannerAdminRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/claims/new': {
      id: '/_authenticated/claims/new'
      path: '/claims/new'
      fullPath: '/claims/new'
      preLoaderRoute: typeof AuthenticatedClaimsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/batch': {
      id: '/_authenticated/claims/batch'
      path: '/claims/batch'
      fullPath: '/claims/batch'
      preLoaderRoute: typeof AuthenticatedClaimsBatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims/$claimId': {
      id: '/_authenticated/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cat-report/$deploymentId': {
      id: '/_authenticated/cat-report/$deploymentId'
      path: '/cat-report/$deploymentId'
      fullPath: '/cat-report/$deploymentId'
      preLoaderRoute: typeof AuthenticatedCatReportDeploymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerAdminRoute: typeof AuthenticatedPlannerAdminRoute
  AuthenticatedPlannerFieldDayRoute: typeof AuthenticatedPlannerFieldDayRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerAdminRoute: AuthenticatedPlannerAdminRoute,
  AuthenticatedPlannerFieldDayRoute: AuthenticatedPlannerFieldDayRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRoute
  AuthenticatedModeSelectRoute: typeof AuthenticatedModeSelectRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedCatReportDeploymentIdRoute: typeof AuthenticatedCatReportDeploymentIdRoute
  AuthenticatedClaimsClaimIdRoute: typeof AuthenticatedClaimsClaimIdRoute
  AuthenticatedClaimsBatchRoute: typeof AuthenticatedClaimsBatchRoute
  AuthenticatedClaimsNewRoute: typeof AuthenticatedClaimsNewRoute
  AuthenticatedClaimsIndexRoute: typeof AuthenticatedClaimsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRoute,
  AuthenticatedModeSelectRoute: AuthenticatedModeSelectRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedCatReportDeploymentIdRoute:
    AuthenticatedCallsRoute,
    AuthenticatedClaimsMapRoute,
    AuthenticatedCatReportDeploymentIdRoute,
  AuthenticatedClaimsClaimIdRoute: AuthenticatedClaimsClaimIdRoute,
  AuthenticatedClaimsBatchRoute: AuthenticatedClaimsBatchRoute,
  AuthenticatedClaimsNewRoute: AuthenticatedClaimsNewRoute,
  AuthenticatedClaimsIndexRoute: AuthenticatedClaimsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
